import React from "react";
import localFont from "next/font/local";
import Card from "./components/card";
import { StyledButton } from "./styles/styles";
import Button from "@mui/material/Button";
import Navbar from "./components/navbar";
// import { useDropdown, } from "./pricing/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ margin: 0, padding: 0, height: "100vh", width: "100vw" }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            gap: 20,
          }}
        >
         
          <Navbar />
          <Navbar />
          <Navbar />
          <Navbar />
          <Navbar />
        </div>

        {/* <div
          style={{
            display: "flex",
            gap: 30,
            color: "black",
            background: "white",
            justifyContent: "center",
            fontSize: 25,
          }}
        >
          <Button variant="text" onClick={useDropdown}>
            home
          </Button>
          <Button variant="text">types</Button>
          <Button variant="text">offers</Button>
          <Button variant="text">about</Button>
          <Button variant="text">cart</Button>
          <Button variant="text">our services</Button>
        </div> */}
        {children}
      </body>
    </html>
  );
}
